name: AI Code Review

on:
  push:
    branches:
      - main  # 可以根据需要修改为其他分支
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-review:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整的git历史记录
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file
      run: |
        echo "WECHAT_APPID=wx6407bd04526890ef" >> .env
        echo "WECHAT_SECRET=51df33ed6853726d2a38bbbdfcbc0429" >> .env
        echo "WECHAT_TEMPLATE_ID=KbF7tOkw01wcmb-9u0rrkqpXB4tH-Fmojw5sChrMY64" >> .env
        echo "DEEPSEEK_API_KEY=sk-67b7e4b57fc44664945a1fff523e1e1f" >> .env
        echo "DEEPSEEK_API_URL=https://api.deepseek.com/v1/chat/completions" >> .env
        echo "CODE_TOKEN=${{ secrets.CODE_TOKEN }}" >> .env
        echo "GITHUB_REPO=Jie258079/openai-code-review-python" >> .env
    
    - name: Run code review
      run: |
        python src/main.py
      env:
        PYTHONPATH: ${{ github.workspace }}
    
    - name: Handle failure
      if: failure()
      run: |
        echo "Code review process failed. Please check the logs for details."
        exit 1 